name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  name:
    description: 'user.name'
    required: false
    default: 'github-actions[bot]'
  email:
    description: 'user.email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: |
        git config user.name $INPUT_NAME
        git config user.email $INPUT_EMAIL
      shell: bash
