name: Awesome Nostr Japan
description: Add
title: "[Add] "
assignees:
  - SnowCait
body:
  - type: input
    attributes:
      label: Relay name
    validations:
      required: true
  - type: input
    attributes:
      label: Relay URL
    validations:
      required: true
