services:
  mysql:
    image: mysql:8.0.34
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
