version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
    ports:
      - "3306:3306"
    volumes:
      - .database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
