version: "3.9"

services:
  mysql-server:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  mysql-client: # 実際は Node.js や PHP などのアプリコンテナ
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
