credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: pat
          scope: GLOBAL
          username: "SnowCait"
          password: "${PAT}"
jenkins:
  globalNodeProperties:
  - envVars:
      env:
      - key: VARIABLE1
        value: foo
      - key: VARIABLE2
        value: bar
jobs:
  - script: |
      pipelineJob('job-sandbox') {
        definition {
          cps {
            script('''\
              pipeline {
                  agent any
                  stages {
                      stage('checkout') {
                          steps {
                              sh 'ls -la'
                              checkout scm: [
                                  $class: 'GitSCM',
                                  branches: [[ name: "refs/heads/main" ]],
                                  userRemoteConfigs: [
                                      [
                                          url: 'https://github.com/SnowCait/private-repository',
                                          credentialsId: 'pat'
                                      ]
                                  ]
                              ]
                              sh 'ls -la'
                          }
                      }
                      stage('failure') {
                          steps {
                              echo 'step failure'
                              //error('failure!')
                          }
                      }
                  }
              }
            '''.stripIndent())
            sandbox()
          }
        }
      }
