jenkins:
  globalNodeProperties:
  - envVars:
      env:
      - key: VARIABLE1
        value: foo
      - key: VARIABLE2
        value: bar
jobs:
  - script: |
      pipelineJob('job-failure') {
        definition {
          cps {
            script('''
            pipeline {
                agent any
                stages {
                    stage('failure') {
                        steps {
                            echo 'step 1'
                            //error('failure!')
                        }
                    }
                }
            }
            '''.stripIndent())
            sandbox()
          }
        }
      }
