name: 'PHP AST Changed'
description: 'PHP AST in PR have changed if need debug'

inputs:
  php-version:
    description: 'PHP version'
    required: false
    default: '8.1'
  php-ast-version:
    description: 'PHP AST version'
    required: false
    default: '90'

outputs:
  changed:
    description: '*.php files are changed: "true" (string), not changed: "false" (string)'
    value: ${{ steps.diff.outputs.exists }}

runs:
  using: 'composite'
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ast

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - run: |
        set -x
        if (( $(gh pr view ${pr_number} --json changedFiles --jq '.changedFiles') > 100 )); then
          echo "Changed files are more than 100."
          exit 1
        fi
      env:
        pr_number: ${{ github.event.number }}
      shell: bash
    - run: gh pr view ${pr_number} --json files --jq '.files[].path | select(endswith(".php"))' > ${GITHUB_ACTION_PATH}/paths
      env:
        pr_number: ${{ github.event.number }}
      shell: bash
    - run: cat ${GITHUB_ACTION_PATH}/paths
      shell: bash
    - run: php ${GITHUB_ACTION_PATH}/php-ast.php ${version} ${GITHUB_ACTION_PATH}/paths head
      env:
        version: ${{ inputs.php-ast-version }}
      shell: bash
    - run: cat head
      shell: bash
    - run: git stash -u
      shell: bash

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}
    - run: git stash pop
      shell: bash
    - run: php ${GITHUB_ACTION_PATH}/php-ast.php ${version} ${GITHUB_ACTION_PATH}/paths base
      env:
        version: ${{ inputs.php-ast-version }}
      shell: bash
    - run: cat base
      shell: bash

    - id: diff
      run: |
        if diff head base; then
          echo "::set-output name=exists::false"
        else
          echo "::set-output name=exists::true"
        fi
      shell: bash

branding:
  icon: 'alert-octagon'
  color: 'gray-dark'
