name: 'PHP AST'
description: 'PHP AST'
inputs:
  php-version:
    description: 'PHP version'
    required: false
    default: '8.1'
  php-ast-version:
    description: 'PHP AST version'
    required: false
    default: '90'
  pr-number:
    description: 'PR number'
    required: false
    default: ${{ github.event.number }}
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: 'composite'
  steps:
    - run: printenv
      shell: bash

    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ast

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - run: |
        set -x
        if (( $(gh pr view ${pr_number} --json changedFiles --jq '.changedFiles') > 100 )); then
          echo "Changed files are more than 100."
          exit 1
        fi
      env:
        pr_number: ${{ inputs.pr-number }}
      shell: bash
    - run: gh pr view ${pr_number} --json files --jq '.files[].path | select(endswith(".php"))' > paths
      env:
        pr_number: ${{ inputs.pr-number }}
      shell: bash
    - run: cat paths
      shell: bash
    - run: php ${{ github.action_path }}/php-ast.php ${version} head
      env:
        version: ${{ inputs.php-ast-version }}
      shell: bash
    - run: cat head
      shell: bash

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}
    - run: php ${{ github.action_path }}/php-ast.php ${version} base
      env:
        version: ${{ inputs.php-ast-version }}
      shell: bash
    - run: cat base
      shell: bash

    - run: diff head base
      shell: bash
branding:
  icon: 'award'
  color: 'green'
