name: 'PHP AST Changed'
description: 'PHP AST in PR have changed to judge if debug is necessary or not'

inputs:
  php-version:
    description: 'PHP version'
    required: false
    default: '8.1'
  php-ast-version:
    description: 'PHP AST version'
    required: false
    default: '90'

outputs:
  changed:
    description: '*.php files have changed: "true" (string), not changed: "false" (string)'
    value: ${{ steps.diff.outputs.exists }}

runs:
  using: 'composite'
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ast
    - name: Download util.php
      run: |
        <?php
        declare(strict_types=1);

        $ast_version = phpversion('ast');
        $url = "https://raw.githubusercontent.com/nikic/php-ast/v{$ast_version}/util.php";
        echo $url;

        $contents = file_get_contents("https://raw.githubusercontent.com/nikic/php-ast/v{$ast_version}/util.php");
        file_put_contents('util.php', $contents);
      shell: php {0}

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
#     - run: |
#         set -x
#         if (( $(gh pr view ${pr_number} --json changedFiles --jq '.changedFiles') > 100 )); then
#           echo "Changed files are more than 100."
#           exit 1
#         fi
#       env:
#         pr_number: ${{ github.event.number }}
#       shell: bash
#     - run: gh pr view ${pr_number} --json files --jq '.files[].path | select(endswith(".php"))' > ${GITHUB_ACTION_PATH}/paths
#       env:
#         pr_number: ${{ github.event.number }}
#       shell: bash
    - run: git fetch --depth=1 --no-tags origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      shell: bash
    - run: git diff --name-only origin/${{ github.base_ref }} -- '*.php' > ${GITHUB_ACTION_PATH}/paths
      shell: bash
    - id: paths
      run: echo "::set-output name=json::$(gh pr view ${pr_number} --json files --jq '.files | map(select(.path | endswith(".php"))) | map(.path)')"
      env:
        pr_number: ${{ github.event.number }}
      shell: bash
    - run: echo "${{ steps.paths.outputs.json }}"
      shell: bash
    - run: cat ${GITHUB_ACTION_PATH}/paths
      shell: bash
    - id: head-hashes
      run: php ${GITHUB_ACTION_PATH}/php-ast-hashes.php ${version}
      env:
        version: ${{ inputs.php-ast-version }}
        paths: ${{ steps.paths.outputs.json }}
      shell: bash
    # - run: cat head
    #   shell: bash
    - run: echo "${{ steps.head-hashes.outputs.json }}"
      shell: bash
    # - run: git stash -u
    #   shell: bash

#     - uses: actions/checkout@v3
#       with:
#         ref: ${{ github.base_ref }}
    - run: git switch ${{ github.base_ref }}
      shell: bash
    - id: base-hashes
      run: php ${GITHUB_ACTION_PATH}/php-ast-hashes.php ${version} ${GITHUB_ACTION_PATH}/paths
      env:
        version: ${{ inputs.php-ast-version }}
        paths: ${{ steps.paths.outputs.json }}
      shell: bash
    - run: echo "${{ steps.base-hashes.outputs.json }}"
      shell: bash

    - id: diff
      run: |
        if [ "${head_hashes}" = "${base_hashes}" ]; then
          echo "::set-output name=exists::false"
        else
          echo "::set-output name=exists::true"
        fi
      env:
        head_hashes: ${{ steps.head-hashes.outputs.json }}
        base_hashes: ${{ steps.base-hashes.outputs.json }}
      shell: bash

branding:
  icon: 'alert-octagon'
  color: 'gray-dark'
