version: "3.9"
services:
  phpunit-on-php81:
    image: php:8.1.3-cli
    entrypoint: vendor/bin/phpunit
    working_dir: /src
    volumes:
      - ".:/src"

  phpunit-on-php74:
    image: php:7.4.28-cli
    entrypoint: vendor/bin/phpunit
    working_dir: /src
    volumes:
      - ".:/src"
