name: Bash

on:
  push:
    paths:
      - .github/workflows/bash.yml
  workflow_dispatch:

jobs:
  environment:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: whoami

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      TEXT: a
      NUMBER: 1

    steps:
      - run: test "${TEXT}" = "a"
      - run: "[ \"${TEXT}\" = \"a\" ]"
      - run: "[[ \"${TEXT}\" == \"a\" ]]"
      - run: (( ${NUMBER} == 1 ))
      - run: test "${TEXT}" != "b"
      - run: '[ "${TEXT}" != "b" ]'
      - run: '[[ "${TEXT}" != "b" ]]'
      - run: (( ${NUMBER} != 2 ))

  sleep:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - run: sleep 30
      - run: sleep 1m 30s
