name: Bash

on:
  push:
    paths:
      - .github/workflows/bash.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEXT: a
      NUMBER: 1

    steps:
      - run: test "${TEXT}" = "a"
      - run: '[ "${TEXT}" = "a" ]'
      - run: '[[ "${TEXT}" == "a" ]]'
      - run: (( ${NUMBER} == 1 ))
      - run: test "${TEXT}" != "b"
      - run: '[ "${TEXT}" != "b" ]'
      - run: '[[ "${TEXT}" != "b" ]]'
      - run: (( ${NUMBER} == 2 ))
