name: Bash

on:
  push:
    paths:
      - .github/workflows/bash.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: test "a" = "a"
      - run: '[ "b" = "b" ]'
      - run: '[[ "c" == "c" ]]'
      - run: (( 1 == 1 ))
      - run: test "a" != "d"
      - run: '[ "b" != "e" ]'
      - run: '[[ "c" != "f" ]]'
      - run: (( 1 != 2 ))
