name: Checks API

on:
  push:
    paths:
      - .github/workflows/checks.yml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: |
          gh api -X POST repos/${repository}/check-runs -f name="checks test" -f head_sha=${head}
        env:
          repository: ${{ github.repository }}
          head: ${{ github.ref }}
