name: CI

on:
  pull_request:

jobs:
  paths:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    outputs:
      client: ${{ steps.changes.outputs.client == 'true' || steps.changes.outputs.workflow == 'true' }}
      server: ${{ steps.changes.outputs.server == 'true' || steps.changes.outputs.workflow == 'true' }}
      workflow: ${{ steps.changes.outputs.workflow == 'true' }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'
            workflow:
              - '.github/workflows/ci.yml'

  client-lint:
    needs: [ paths ]
    if: needs.paths.outputs.client == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - run: sh build.sh

  client-test:
    needs: [ paths ]
    if: needs.paths.outputs.client == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - run: sh build.sh
      - run: sh test.sh

  server-lint:
    needs: [ paths ]
    if: needs.paths.outputs.server == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - run: sh test.sh

  server-test:
    needs: [ paths ]
    if: needs.paths.outputs.server == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - run: sh test.sh

  workflow-lint:
    needs: [ paths ]
    if: needs.paths.outputs.workflow == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1.27.0
        with:
          actionlint_flags: -shellcheck= -pyflakes=
      - uses: reviewdog/action-yamllint@v1.6.1
        with:
          yamllint_flags: -c .github/.yamllint .github/workflows/


  # Required status checks and Notification
  passing:
    needs:
      - client-lint
      - client-test
      - server-lint
      - server-test
      - workflow-lint
    if: always()
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      number: ${{ github.event.number }}
      sha: ${{ github.event.pull_request.head.sha }}  # 厳密には github.sha だが PR 上での分かりやすさを優先する
      author: ${{ github.actor }}

    steps:
      - run: echo "$json"
        env:
          json: ${{ toJSON(needs) }}
      - name: PR
        id: pr
        run: echo "::set-output name=json::$(gh api repos/${GITHUB_REPOSITORY}/pulls/${number})"
      - name: Success or Skipped
        run: gh pr comment $number --body "@${author} CI passing at ${sha}"
        if: >-
          contains(needs.*.result, 'failure') == false &&
          contains(needs.*.result, 'cancelled') == false &&
          github.event.pull_request.head.sha == fromJSON(steps.pr.outputs.json).head.sha
      - name: Failure or Cancelled
        run: |
          echo '[failure]'
          echo "$needs" | jq -r 'to_entries | map(select(.value.result == "failure")) | .[].key'
          echo '----------'
          echo '[cancelled]'
          echo "$needs" | jq -r 'to_entries | map(select(.value.result == "cancelled")) | .[].key'
          echo '----------'
          gh pr comment $number --body "@${author} CI failure at ${sha}"
          exit 1
        env:
          needs: ${{ toJSON(needs) }}
        if: >-
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
