name: CI

on:
  pull_request:

jobs:
  paths:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    outputs:
      client: ${{ steps.changes.outputs.client }}
      server: ${{ steps.changes.outputs.server }}

    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            client:
              - 'client/**'
            server:
              - 'server/**'

  build-client:
    needs: [ paths ]
    if: needs.paths.outputs.client == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - run: exit 1
      - run: sh build.sh

  test-client:
    needs: [ paths ]
    if: needs.paths.outputs.client == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - run: sh test.sh

  test-server:
    needs: [ paths ]
    if: needs.paths.outputs.server == 'true'
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - run: sh test.sh

  passing:
    needs: [ build-client, test-client, test-server ]
    if: failure() == false && contains(needs.*.result, 'cancelled') == false
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - run: echo "$json"
        env:
          json: ${{ toJSON(needs) }}
      - run: gh pr comment $number --body "@${author} CI passing"
        env:
          number: ${{ github.event.number }}
          author: ${{ github.event.user.login }}

  post:
    needs: [ passing ]
    if: failure() == false
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - run: echo 'Run post script'

  failure:
    needs: [ build-client, test-client, test-server ]
    if: failure()
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - run: gh pr comment $number --body "@${author} CI failed"
        env:
          number: ${{ github.event.number }}
          author: ${{ github.event.user.login }}

  cancelled:
    needs: [ build-client, test-client, test-server ]
    if: cancelled()
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - run: gh pr comment $number --body "@${author} CI cancelled or timed-out"
        env:
          number: ${{ github.event.number }}
          author: ${{ github.event.user.login }}
