name: Concurrency

on:
  push:
    paths:
      - .github/workflows/concurrency.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      WORKFLOW: ${{ github.workflow }}

    steps:
      - run: gh run list --workflow ${WORKFLOW}

      - run: gh api -X GET repos/${GITHUB_REPOSITORY}/actions/runs | jq '.[].status'

      - run: gh api -X GET repos/${GITHUB_REPOSITORY}/actions/runs --field status=in_progress

      - run: gh api -X GET repos/${GITHUB_REPOSITORY}/actions/runs --field workflow_id=${WORKFLOW}

      - name: Sleep 10 minutes
        run: sleep 600
