name: Concurrency

on:
  push:
    paths:
      - .github/workflows/concurrency.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Control concurrency
        run: gh run list
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}

      - name: Sleep 10 minutes
        run: sleep 600
