name: cURL

on:
  push:
    paths: .github/workflows/curl.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: curl --fail --output openapi.json https://api.twitter.com/2/openapi.json # https://api.twitter.com/labs/1/openapi.json
      - run: cat openapi.json
