name: Default branch

on:
  push:
    paths:
      - .github/workflows/default-branch.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.repository.default_branch }}
      
      # API
      - uses: octokit/request-action@v2.1.7
        id: repo
        with:
          route: GET /repos/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # or ${{ github.token }}
      - run: echo ${{ fromJson(steps.repo.outputs.data).default_branch }}

      # Checkout
      - uses: actions/checkout@v3
        with:
          repository: SnowCait/rest-api-description
      - run: git rev-parse --abbrev-ref HEAD
