name: Delete workflow

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: workflow-id, workflow-name or filename
        required: true
        type: string

jobs:
  delete:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      WORKFLOW: ${{ github.event.inputs.workflow }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: gh workflow list --all
      - run: gh workflow view "${WORKFLOW}"
      - run: gh run list --workflow "${WORKFLOW}"
      - run: gh run list --workflow "${WORKFLOW}" --json databaseId,status,workflowDatabaseId
      - run: gh run list --workflow "${WORKFLOW}" --json databaseId,status --jq '.[] | select(.status != "in_progress") | .databaseId'
      - run: |
          gh run list --workflow "${WORKFLOW}" --json databaseId,status --jq '.[] | select(.status != "in_progress") | .databaseId' \
            | xargs -n 1 echo "run_id: "
