name: Deno

on:
  push:
    paths:
      - .github/workflows/deno.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: denoland/setup-deno@v1
      - run: deno --version
      - run: |
          await new Promise((resolve) => {
            const ws = new WebSocket('wss://yabu.me/');
            ws.addEventListener('open', () => {
              console.log('open');
              ws.close();
              resolve();
            });
          });
        shell: deno run --allow-net {0}
