name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-sandbox:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - run: echo "Deploy to sandbox"

  deploy-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - run: echo "Deploy to production"
