name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-sandbox:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - run: echo "Deploy to sandbox"
      - run: echo $GITHUB_REF_NAME
      - run: echo $secret
        env:
          secret: ${{ secrets.ENV_SECRET }}

  deploy-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - run: echo "Deploy to production"
      - run: echo $GITHUB_REF_NAME
      - run: echo $secret
        env:
          secret: ${{ secrets.ENV_SECRET }}
