name: Docker

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - docker/**

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      COMPOSE_INTERACTIVE_NO_CLI: true
    defaults:
      run:
        working-directory: docker

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: docker-compose ps
      - run: sleep 120
      - run: docker-compose ps
      - run: docker-compose exec mysql mysql -V
      - run: docker-compose exec mysql mysql -uroot -e "SHOW DATABASES"
      - run: docker-compose logs
        if: always()

  service:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: abcdef
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MYSQL_PASSWORD: abcdef

    steps:
      - run: docker ps
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(job.services) }}
      - run: mysql -V
      - run: mysql -–protocol=tcp -hlocalhost -P3306 -uroot -e "SHOW DATABASES"
      - run: docker logs $(docker ps -q)
        if: always()
