name: Docker Image CI

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - docker/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docker

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d
    - run: sleep 120
    - run: docker-compose exec mysql mysql -V
    - run: docker-compose exec mysql mysql -uroot -e "SHOW DATABASES"
    - run: docker-compose logs
      if: always()
