name: Early Exit

on:
  push:

jobs:
  step-if:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CONTINUE=$((RANDOM % 2))" >> $GITHUB_ENV
      - run: echo $CONTINUE
      - run: echo a
      - run: echo b
        if: env.CONTINUE == 1
      - run: echo c
        if: env.CONTINUE == 1

  shell-script:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CONTINUE=$((RANDOM % 2))" >> $GITHUB_ENV
      - run: echo $CONTINUE
      - run: |
          echo a
          if [ $CONTINUE -ne 1 ]; then
            exit 0
          fi
          echo b
          echo c
