name: Early Exit

on:
  push:

jobs:
  step-if:
    runs-on: ubuntu-latest
    steps:
      - run: echo "BOOL=$((RANDOM % 2))" >> GITHUB_ENV
      - run: echo $BOOL
      - run: echo a
      - run: echo b
        if: env.BOOL == 0
      - run: echo c
        if: env.BOOL == 0

  shell-script:
    runs-on: ubuntu-latest
    steps:
      - run: echo a
      - run: echo b
      - run: echo c
