name: Early Exit

on:
  push:

jobs:
  step-if:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CONTINUE=$((RANDOM % 2))" >> $GITHUB_ENV
      - run: echo $CONTINUE
      - run: echo a
      - run: echo b
        if: env.CONTINUE
      - run: echo c
        if: env.CONTINUE

  shell-script:
    runs-on: ubuntu-latest
    steps:
      - run: echo a
      - run: echo b
      - run: echo c
