name: Expression

on:
  push:
    paths:
      - .github/workflows/expression.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - run: sleep 2m
        timeout-minutes: 1
      - run: echo success
        if: success()
      - run: echo cancelled
        if: cancelled()
      - run: echo failure
        if: failure()
