name: Expression

on:
  push:
    paths:
      - .github/workflows/expression.yml
  workflow_dispatch:

jobs:
  job-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: sleep 2m
        id: timeout
      - run: echo success
        if: success()
      - run: echo cancelled
        if: cancelled()
      - run: echo failure
        if: failure()
      - run: echo "$json"
        env:
          json: ${{ toJSON(steps) }}
        if: cancelled()

  step-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - run: sleep 2m
        timeout-minutes: 1
        id: timeout
      - run: echo success
        if: success()
      - run: echo cancelled
        if: cancelled()
      - run: echo failure
        if: failure()
      - run: echo "$json"
        env:
          json: ${{ toJSON(steps) }}
        if: failure()

  failure:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - run: exit 1
        id: failure
      - run: echo success
        if: success()
      - run: echo cancelled
        if: cancelled()
      - run: echo failure
        if: failure()
      - run: echo "$json"
        env:
          json: ${{ toJSON(steps) }}
        if: failure()
