name: Follow branch

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - run: git fetch --no-tags --prune --unshallow
    - run: git checkout -B default origin/default
    - run: git merge --ff-only origin/master
    - run: git push origin default
