name: Git config user

on:
  push:
    paths:
      - .github/workflows/git-config-user.yml
  workflow_dispatch:

jobs:
  test-bash:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-2022, windows-2019 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - run: echo "${{ toJSON(runner) }}"
# fatal: not in a git directory
#       - uses: snow-actions/git-config-user@git-config-user
#       - run: |
#           git config user.name
#           git config user.email
      - uses: actions/checkout@v5
      - uses: snow-actions/git-config-user@v1.0.0
      - run: |
          git config user.name
          git config user.email
      - run: test "$(git config user.name)" = "github-actions[bot]"
      - run: test "$(git config user.email)" = "41898282+github-actions[bot]@users.noreply.github.com"
      - run: echo "test" > test
      - run: git add .
      - run: git commit -m "test"
      - run: echo "${GREET}"
        env:
          GREET: hello
      - run: test $env:GREET = "hello"
        env:
          GREET: hello
        if: runner.os == 'Windows'
      - run: test "${GREET}" = "hello"
        env:
          GREET: hello
        if: runner.os != 'Windows'
