name: GitHub Stars

# https://github.com/search?q=stars:%3E1&s=stars&type=Repositories
# https://qiita.com/notakaos/items/e344bbeca52e41df443a

on:
  push:
    paths:
      - .github/workflows/github-stars.yml
      - .github/workflows/github-stars.js
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
#       - run: gh api "/search/repositories?q=stars:%3E10000&s=stars&type=Repositories&per_page=5" | jq '.'
#       - run: gh api "/search/repositories?q=stars:%3E1&s=stars&type=Repositories&per_page=5" | jq '.items | map(.full_name)'
#       - run: gh api "/repos/${GITHUB_REPOSITORY}/git/trees/main" | jq '.'
      - run: gh api "/repos/${GITHUB_REPOSITORY}/contents/" | jq '.'
      - run: gh api "/repos/${GITHUB_REPOSITORY}/contents/.github/workflows/" | jq '.'
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/workflows/github-stars.js');
            await script({github});
