name: github-script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            const json = {"a": 1}
            await fs.writeFile('./ci-services.json', JSON.stringify(result, null, 2));
      - run: git diff
