name: github-script

on:
  push:
    paths:
      - .github/workflows/github-script.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v5
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            const json = {"a": 1}
            await fs.writeFile('./sample.json', JSON.stringify(json, null, 2));
      - run: ls -la
      - run: cat sample.json
      - run: |
          git add -N .
          git diff
