name: Icon

on:
  push:
    paths:
      - .github/workflows/icon.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FILE: Twitter_Logo_Blue.png

    steps:
      - uses: actions/checkout@v2
      - run: identify $FILE
      - run: test "$(identify $FILE | cut -f 2,6 -d ' ')" = "PNG sRGB"
