name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      jenkins:
        image: jenkins/jenkins:lts-jdk11
        ports:
          - 8080:8080
          - 50000:50000
        options: >-
          --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
          --health-cmd "ping http://localhost:8080/"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 60s

    steps:
      - run: curl -sSL http://0.0.0.0:8080/
