name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      jenkins:
        image: jenkins/jenkins:lts-jdk11
        env:
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
          - 8080:8080
          - 50000:50000
        volumes:
          - ${{ github.workspace }}/jenkins/jenkins_home/jobs:/var/jenkins_home/jobs
        options: >-
          --health-cmd "curl -f http://localhost:8080/"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 70s

    steps:
      - run: curl -sSL http://localhost:8080/
      - run: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket help
      - uses: actions/checkout@v3
