name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: jenkins/jenkins:lts-jdk11
      ports:
        - 8080
        - 50000

    steps:
      - run: cat /var/jenkins_home/secrets/initialAdminPassword
