name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container: chickenzord/jenkins-cli:latest
    timeout-minutes: 30
    env:
      JENKINS_URL: http://localhost:8080
    defaults:
      run:
        working-directory: /jenkins-cli

    services:
      jenkins:
        image: jenkins/jenkins:lts-jdk11
        env:
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
          - 8080:8080
          - 50000:50000
        options: >-
          --health-cmd "curl -f ${{ env.JENKINS_URL }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 30s

    steps:
      - run: pwd
      - run: ls -la
#       - run: curl -sSL http://localhost:8080/
      
      - run: ./jenkins-cli-wrapper.sh help
      
#       - run: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
#       - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket help

      - uses: actions/checkout@v3
      - run: curl -X POST http://localhost:8080/job/job-1/build
