name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      jenkins:
        image: jenkins/jenkins:lts-jdk11
        env:
          JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
          - 8080:8080
          - 50000:50000
        options: >-
          --health-cmd "curl -f http://localhost:8080/"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 30s

    steps:
      - run: curl -sSL http://localhost:8080/
      - uses: actions/checkout@v3
      
      - run: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket help
#       - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket install-plugin '=' < jenkins/plugins.txt
      - uses: srz-zumix/setup-service-jenkins@v1.1.0
        with:
          id: "${{ job.services.jenkins.id }}"
          install_suggested_plugins: true
      
#       - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket create-job job-1 < jenkins/jenkins_home/jobs/job-1/config.xml
      - run: jenkins-cli list-plugins
      - run: jenkins-cli create-job job-1 < jenkins/jenkins_home/jobs/job-1/config.xml
      - run: curl -X POST http://localhost:8080/job/job-1/build
