name: jenkinsci/docker

on:
  push:
    paths:
      - .github/workflows/jenkinsci.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - run: |
          docker run -d -p 8080:8080 -p 50000:50000 --restart=on-failure \
          --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" \
          --env JENKINS_UC=https://updates.jenkins.io/current \
          jenkins/jenkins:lts-jdk11
      - name: Wait for starting
        run: sleep 20s
      - run: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket version
      - run: curl -sS https://updates.jenkins.io/update-center.json
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket install-plugin git -deploy
      
