name: Jobs

on:
  push:
    paths:
      - .github/workflows/jobs.yml

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo job1
#       - run: exit 1

  job2:
    needs: [ job1 ]
    if: failure()
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo job2
