name: JSON

on:
  push:
    paths:
      - .github/workflows/json.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - id: event
        run: echo "::set-output name=json::$(cat $GITHUB_EVENT_PATH)"
      - run: echo $JSON
        env:
          JSON: ${{ steps.event.outputs.json }}
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(github.event) }}
