name: PavanMudigonda/lines-of-code-reporter
on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/lines-of-code-reporter.yml
  workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Calculate Lines of Code
        id: loc
        uses: PavanMudigonda/lines-of-code-reporter@v1.6   

      # Publish Lines of Code Summary  # Optional
      - name: Add Lines of Code Summary
        run: cat "${{ steps.loc.outputs.loc_report }}" >> $GITHUB_STEP_SUMMARY

      - name: print output # Optional
        shell: pwsh
        run: | 
          Write-Host 'Total Lines of Code...:  ${{ steps.loc.outputs.total_lines }}'
          Write-Host 'Lines of Code Markdown Report Path...:  ${{ steps.loc.outputs.loc_report }}' 
