name: LINE Notify
on:
  issues:
    types: opened
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            Issue is opened.
            #${{ github.event.issue.number }}: ${{ github.event.issue.title }}
