name: Lint

on:
  pull_request:
    paths:
      - .github/.yamllint
      - .github/workflows/*.yml
  workflow_dispatch:

# env:
#   GH_TOKEN: ${{ github.token }}

jobs:
#   yamllint:
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       - run: cat $GITHUB_EVENT_PATH
#       - uses: actions/checkout@v3
#       - run: gh pr view $number --json files --jq '.files[].path'
#         env:
#           number: ${{ github.event.number }}
#       - run: yamllint -c .github/.yamllint $(gh pr view $number --json files --jq '.files[].path')

  yamllint-with-reviewdog:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-yamllint@v1.6.0
        with:
          yamllint_flags: -c .github/.yamllint .github/workflows/

  actionlint-with-reviewdog:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
