name: Lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yml
  workflow_dispatch:

jobs:
  github-hosted-yamllint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - run: yamllint workflows/
        working-directory: .github/

#   reviewdog-yamllint:
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       - uses: actions/checkout@v3
#       - uses: reviewdog/action-yamllint@v1.5.1
