name: ls

on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/ls.yml

jobs:
  ls:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      json: ${{ steps.ls.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: ls -l
      - run: ls -A
      - run: ls -d .
      - run: ls | jq -Rs 'split("\n")[:-1]'
      - run: ls | jq -Rsc 'split("\n")[:-1]'
      - uses: snow-actions/ls@v1.0.0
        with:
          path: docs
        id: ls
  path:
    needs: [ ls ]
    strategy:
      matrix:
        path: ${{ fromJSON(needs.ls.outputs.json) }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo ${{ matrix.path }}
