name: ls

on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/ls.yml

jobs:
  ls:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: ls -l
      - run: ls -A
      - run: ls -d .
      - run: ls | jq -Rs 'split("\n")[:-1]'
      - run: ls | jq -Rsc 'split("\n")[:-1]'
      - run: echo "${{ toJSON(runner) }}"
