name: Matrix

on:
  push:
    paths:
      - .github/workflows/matrix.yml
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-20.04, ubuntu-18.04 ]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 5

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo 'ubuntu-20.04'
        if: matrix.runner == 'ubuntu-20.04'
