name: Merge

on:
#   pull_request:
  workflow_dispatch:
    inputs:
      pr_number:
        type: number
        required: true
        description: PR number

jobs:
  merge:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: gh --version
      - uses: actions/checkout@v3
#       - run: gh pr merge $PR_NUMBER --merge --delete-branch
#         env:
#           GH_TOKEN: ${{ github.token }}
#           PR_NUMBER: ${{ github.event.inputs.pr_number }}
      - name: Instead of gh pr merge $PR_NUMBER --merge --delete-branch
        run: |
          set -x
          gh pr merge $PR_NUMBER --merge
          json=$(gh pr view $PR_NUMBER --json baseRefName,headRefName)
          base=$(echo $json | jq -r '.baseRefName')
          head=$(echo $json | jq -r '.headRefName')
          numbers=$(gh pr list --base ${head} --limit 100 --json number --jq '.[].number')
          for number in ${numbers[@]}; do
            gh pr edit $number --base ${base}
          done
          gh api -X DELETE repos/${REPOSITORY}/git/refs/heads/${head}
        env:
          GH_TOKEN: ${{ github.token }} # Should be secrets.YOUR_TOKEN if you want to trigger next workflow.
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
#       - name: Instead of gh pr merge $PR_NUMBER --merge --delete-branch
#         run: |
#           set -x
#           gh pr merge $PR_NUMBER --merge
#           numbers=$(gh pr list --base ${HEAD} --limit 100 --json number --jq '.[].number')
#           for number in ${numbers[@]}; do
#             gh pr edit $number --base ${BASE}
#           done
#           gh api -X DELETE repos/${REPOSITORY}/git/refs/heads/${HEAD}
#         env:
#           GH_TOKEN: ${{ github.token }} # Should be secrets.YOUR_TOKEN if you want to trigger next workflow.
#           REPOSITORY: ${{ github.repository }}
#           PR_NUMBER: ${{ github.event.number }}
#           BASE: ${{ github.base_ref }}
#           HEAD: ${{ github.head_ref }}
