name: Merged

on:
  pull_request:
    types: [ closed ]

jobs:
  merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $GITHUB_HEAD_REF
