name: Milestone of PR

on:
  pull_request:
    types: [ opened, edited ]
    branches:
      - milestone/**

jobs:
  set-milestone:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: Set milestone
        run: gh pr edit ${PR_NUMBER} --milestone ${GITHUB_BASE_REF#milestone/}
