name: Milestone branch

on:
  create:
  delete:

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}
  BRANCH: ${{ github.event.ref }}

jobs:
  create:
    if: github.event_name == 'create' && startsWith(github.event.ref, 'milestone/')
    runs-on: ubuntu-20.04
    timeout-minutes: 1

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_EVENT_NAME
      - run: |
          set -x
          if ! $(gh api -X GET /repos/${GITHUB_REPOSITORY}/milestones --jq ". | any(.title == \"${BRANCH#milestone/}\")"); then
            gh api -X POST repos/${GITHUB_REPOSITORY}/milestones -f title=${BRANCH#milestone/}
          fi

  delete:
    if: github.event_name == 'delete' && startsWith(github.event.ref, 'milestone/')
    runs-on: ubuntu-20.04
    timeout-minutes: 1

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_EVENT_NAME
      - run: |
          set -x
          milestone_number=$(gh api -X GET /repos/${GITHUB_REPOSITORY}/milestones --jq ". | map(select(.title == \"${BRANCH#milestone/}\")) | first | .number")
          gh api -X DELETE /repos/${GITHUB_REPOSITORY}/milestones/${milestone_number}
