name: Milestone

on:
  pull_request:
    branches:
      - milestone/**

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - run: gh pr edit ${PR_NUMBER} --milestone ${GITHUB_BASE_REF#milestone/}
      - run: gh pr edit ${PR_NUMBER} --add-label ${GITHUB_BASE_REF#milestone/}
