name: MySQL

on:
  push:
    paths:
      - .github/workflows/mysql.yml
  workflow_dispatch:

jobs:
  mysql:
    runs-on: ubuntu-latest

    steps:
      - run: mysql -V
      - run: docker image ls
      - run: |
          <?php
          $driver = new mysqli_driver();
          var_dump($driver);
          var_dump($driver->client_info);
          var_dump($driver->client_version);
          var_dump($driver->report_mode);
          $driver->report_mode = MYSQLI_REPORT_OFF;
          var_dump($driver->report_mode);
        shell: php {0}
