name: MySQL

on:
  push:
    paths:
      - .github/workflows/mysql.yml
  workflow_dispatch:

jobs:
  mysql:
    runs-on: ubuntu-latest

    steps:
      - run: mysql -V
      - run: docker image ls
      - run: |
          <?php
          phpinfo();
        shell: php {0}
