name: needs

on:
  push:
    paths:
      - .github/workflows/needs.yml

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo
  job-2:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo
  passing:
    needs: [ job-1, job-2 ]
    if: ${{ !failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "$needs"
        env:
          needs: toJSON(needs)
