name: Node.js

on:
  push:
    paths: .github/workflows/nodejs.yml

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2.3.4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
    - run: npm --version
    - run: npx --version
