name: Nostr

on:
  push:
    paths:
      - .github/workflows/nostr.yml

jobs:
  nostr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: snow-actions/nostr@main
        with:
          relays: |
            wss://relay.nostr.wirednet.jp
            wss://nostr-relay.nokotaro.com
            wss://nostr.fediverse.jp
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY_HEX }}
          content: |
            test
