name: Nostr

on:
  push:
    paths:
      - .github/workflows/nostr.yml

jobs:
  nostr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: snow-actions/nostr@main
        id: publish
        with:
          relays: |
            wss://relay.nostr.wirednet.jp
          private-key: ${{ secrets.NOSTR_PRIVATE_KEY_HEX }}
          content: |
            テスト
      - run: |
          curl -X POST -u "${auth}" -H "Content-Type: application/json" -d "$event" https://nostr-webhook.compile-error.net/post
        env:
          event: ${{ steps.publish.outputs.event }}
          auth: ${{ secrets.NOSTR_WEBHOOK_BASIC_AUTH }}
