name: Nostr Bots

on:
  push:
    paths:
      - nostr/nostr-bot-domains.json
      - .github/workflows/nostr-bots.yml
  workflow_dispatch:

jobs:
  generate-bots-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat nostr/nostr-bot-domains.json
