name: Nostr BOT Metadata

on:
  push:
    branches:
      - main
    paths:
      - metadata.json
  workflow_dispatch:

permissions: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - id: metadata
        run: echo "json=$(cat nostr-bot/metadata.json | jq -c)" >> "$GITHUB_OUTPUT"
      - uses: snow-actions/nostr@v1.7.0
        with:
          kind: 0
          content: ${{ steps.metadata.outputs.json }}
          relays: |
            http://127.0.0.1:8787
          private-key: ${{ secrets.NOSTR_BOT_PRIVATE_KEY }}
