name: PHP AST

on:
  push:
    paths:
      - .github/workflows/php-ast.yml

permissions:
  contents: read

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ast
      - run: |
          <?php
          var_dump(extension_loaded('ast'));
          
          file_put_contents('util.php', file_get_contents('https://raw.githubusercontent.com/nikic/php-ast/master/util.php'));
          require 'util.php'
          
          echo ast_dump(ast\parse_file('php-ast/index.php', $version = 90));
        shell: php {0}
