name: PHP AST

on:
  pull_request:
    paths:
      - .github/actions/php-ast/action.yml
      - .github/workflows/php-ast.yml
      - '**.php'

# permissions:
#   contents: read
#   repository-projects: read # https://github.com/cli/cli/discussions/5307

jobs:
  parse:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ast
      - run: |
          <?php
          file_put_contents('util.php', file_get_contents('https://raw.githubusercontent.com/nikic/php-ast/master/util.php'));
          require 'util.php';

          $ast = ast\parse_file('php-ast/index.php', $version = 90);
          echo ast_dump($ast);
          echo '-------' . PHP_EOL;
          echo md5(ast_dump($ast));
        shell: php {0}

  diff:
    if: github.event_name == 'pull_request'
    runs-on: macos-latest
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
#       - run: cat $GITHUB_EVENT_PATH
#       - uses: actions/checkout@v3
#       - uses: ./.github/actions/php-ast
      - uses: snow-actions/php-ast-changed@main
        id: php-ast
      - name: Label
        run: |
          set -x
          label='needless-debug'
          if [ "${changed}" = 'false' ]; then
            gh pr edit ${{ github.event.number }} --add-label ${label}
          else
            gh pr edit ${{ github.event.number }} --remove-label ${label}
          fi
        env:
          changed: ${{ steps.php-ast.outputs.changed }}
