name: PHP AST

on:
#   push:
#     paths:
#       - .github/workflows/php-ast.yml
  pull_request:
    paths:
      - '**.php'

permissions:
  contents: read

jobs:
  parse:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ast
      - run: |
          <?php
          file_put_contents('util.php', file_get_contents('https://raw.githubusercontent.com/nikic/php-ast/master/util.php'));
          require 'util.php';

          $ast = ast\parse_file('php-ast/index.php', $version = 90);
          echo ast_dump($ast);
          echo '-------' . PHP_EOL;
          echo md5(ast_dump($ast));
        shell: php {0}

  diff:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: |
          set -x
          if (( $(gh pr view ${PR_NUMBER} --json changedFiles --jq '.changedFiles') > 100 )); then
            echo "Changed files are more than 100."
            exit 1
          fi
      - run: gh pr view ${PR_NUMBER} --json files --jq '.files[].path | select(endswith(".php"))' > paths
      - run: cat paths
      - uses: ./.github/actions/php-ast
