name: Laravel

on:
  push:
    paths:
      - .github/workflows/php.yml

jobs:
  php:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        php-version: [ 8.0, 8.1, 8.2 ]

    steps:
      - run: php -v
      - run: ls -l /usr/bin/php*
      - uses: shivammathur/setup-php@9e33c7b24e0b1044916a401f7ab4862fba3980cd
        with:
          php-version: ${{ matrix.php-version }}
      - run: php -v
      - run: ls -l /usr/bin/php*
#       - uses: actions/checkout@v2
#       - name: Copy .env
#         run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#       - name: Install Dependencies
#         run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#       - name: Generate key
#         run: php artisan key:generate
#       - name: Directory Permissions
#         run: chmod -R 777 storage bootstrap/cache
#       - name: Create Database
#         run: |
#           mkdir -p database
#           touch database/database.sqlite
#       - name: Execute tests (Unit and Feature tests) via PHPUnit
#         env:
#           DB_CONNECTION: sqlite
#           DB_DATABASE: database/database.sqlite
#         run: vendor/bin/phpunit
