name: Pull Request
on:
  pull_request:
    paths: .github/workflows/pull_request.yml
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_WORKSPACE
      - run: cat $GITHUB_EVENT_PATH

      - run: gh --version
      - run: gh pr view $PR_NUMBER
      - run: gh pr view $PR_NUMBER --json files
      - run: gh pr view $PR_NUMBER --json files --jq '.files | map(select(.path | endswith(".yml"))) | map(.additions + .deletions) | add'
      - run: |
          json=$(gh pr view $PR_NUMBER --json additions,deletions,changedFiles)
          echo "$(echo "${json}" | jq '.changedFiles') files changed, " > body
          echo "$(echo "${json}" | jq '.additions') insertions(+), " >> body
          echo "$(echo "${json}" | jq '.deletions') deletions(-)" >> body
          gh pr comment $PR_NUMBER --body-file body
          gh pr comment $PR_NUMBER --body-file - <<EOS
          $(echo "${json}" | jq '.changedFiles') files changed, $(echo "${json}" | jq '.additions') insertions(+), $(echo "${json}" | jq '.deletions') deletions(-)
          EOS

      - uses: actions/checkout@v3
      - run: git status
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: git status
