name: Pull Request Review Comment

on: [pull_request_review_comment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - run: cat $GITHUB_EVENT_PATH
#    - run: echo ${{ github.event.comment.body }}
#    - run: echo LGTM is contained
#      if: contains(github.event.comment.body, 'LGTM')
