name: Pull Request
on:
  pull_request:
    paths: .github/workflows/pull_request.yml
jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: gh pr view --json files --jq '.files[].path | select(endswith(".yml"))'
      - run: git fetch --no-tags origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - run: git diff --name-only origin/${{ github.base_ref }} -- '*.yml'
      - run: git diff --name-only origin/${{ github.base_ref }} -- '**.yml'
      - run: git diff --name-only origin/${{ github.base_ref }} -- '***.yml'
      - run: md5sum .github/workflows/pull_request.yml
      - run: git switch ${{ github.base_ref }}
      - run: md5sum .github/workflows/pull_request.yml
