name: Pusher

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - run: echo "${{ github.ref }},${{ github.event.pusher.name }}" >> pusher.csv
      - run: git add pusher.csv
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: git commit -m "pusher.csv"
#       - run: git push
