name: Runner

on:
  push:
    paths:
      - .github/workflows/runner.yml

jobs:
  info:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - run: arch
      - run: uname -a
      - run: uname -m
      - run: uname -i
      - run: getconf LONG_BIT
      - run: cat /etc/lsb-release
      - run: curl -sS https://json.schemastore.org/github-workflow.json
      - run: curl -sS https://json.schemastore.org/github-workflow.json | jq '.definitions.normalJob.properties["runs-on"].oneOf[0].enum'
      - run: |
          curl -sS https://json.schemastore.org/github-workflow.json \
            | jq '.definitions.normalJob.properties["runs-on"].oneOf | first | .enum | map(select(endswith("-latest") | not)) | map (select(. != "self-hosted"))'
