name: Runner

on:
  push:
    paths:
      - .github/workflows/runner.yml

jobs:
  info:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      runners: ${{ steps.list.outputs.json }}

    steps:
      - run: arch
      - run: uname -a
      - run: uname -m
      - run: uname -i
      - run: getconf LONG_BIT
      - run: cat /etc/lsb-release
      - run: curl -sS https://json.schemastore.org/github-workflow.json
      - run: curl -sS https://json.schemastore.org/github-workflow.json | jq '.definitions.normalJob.properties["runs-on"].oneOf[0].enum'
      - run: |
          json=$(curl -sS https://json.schemastore.org/github-workflow.json \
            | jq -c '.definitions.normalJob.properties["runs-on"].oneOf | map(select(.type == "string")) | first | .enum | map(select(endswith("-latest") | not)) | map (select(. != "self-hosted"))')
          echo "json=${json}" >> $GITHUB_OUTPUT
        id: list

  do:
    needs: [ info ]
    strategy:
      matrix:
        runners: ${{ toJSON(needs.info.outputs.runners) }}
    runs-on: ${{ matrix.runner }}
    steps:
      - run: echo $RUNNER_OS
