name: runs-on

on:
  pull_request:
  workflow_dispatch:
    inputs:
      runner:
        description: Select runner
        required: true
        default: ubuntu-20.04
        type: choice
        options:
          - 'ubuntu-20.04'
          - "ubuntu-22.04"
          - windows-2022
          - windows-2019
          - macos-12
          - macos-11
          - self-hosted
          - '[ "self-hosted", "Windows" ]'
          - '[ "ubuntu-20.04" ]'

jobs:
  ubuntu:
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'Windows')
    runs-on: ubuntu-20.04

    steps:
      - run: cat $GITHUB_EVENT_PATH

  windows:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'Windows')
    runs-on: windows-2022

    steps:
      - run: cat $Env:GITHUB_EVENT_PATH

  test:
    if: github.event_name == 'pull_request'
    runs-on: >-
      contains(github.event.pull_request.labels.*.name, 'low-priority')
        && fromJSON('[ "self-hosted", "Windows", "low-priority" ]')
        || fromJSON('[ "self-hsoted", "Windows" ]')

    steps:
      - run: cat $Env:GITHUB_EVENT_PATH

  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ fromJSON(github.event.inputs.runner) }}
    timeout-minutes: 5

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $ImageOS
