name: Schedule

on:
  schedule:
#     - cron: '50 4 * * *' # 10:00 JST
    - cron: '* * * * *' # 19:00 JST
#   workflow_dispatch:
#     inputs:
#       job:
#         description: 'Select job'
#         required: true
#         type: choice
#         options:
#           - ''
#           - start
#           - stop

jobs:
  start:
    if: github.event.schedule == '50 4 * * *'
#     if: github.event.schedule == '30 4 * * *' || github.event.inputs.job == 'start'
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: 開始コマンド
        run: echo ${{ github.event.schedule }}
#         run: aws ec2 start-instances --instance-ids instance-1 instance-2

  stop:
#     if: github.event.schedule == '* * * * *' || github.event.inputs.job == 'stop'
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: 停止コマンド
        run: echo ${{ github.event.schedule }}
#         run: aws ec2 stop-instances --instance-ids instance-1 instance-2
