name: Secrets

on:
  push:
    paths:
      - .github/workflows/secrets.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ secrets.ABC }}
      - run: echo abc
      - run: test "${{ secrets.ABC }}" = "abc"
      - run: echo "${{ secrets.ABC }}" > secrets
      - uses: actions/upload-artifact@v5
        with:
          name: abc
          path: secrets
