name: Self workflow

on:
  push:
    paths:
      - .github/workflows/self-workflow.yml
  workflow_dispatch:
    inputs:
      id:
        default: '123'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - run: printenv
      - run: gh workflow view "$GITHUB_WORKFLOW"
      - run: gh workflow view "$GITHUB_WORKFLOW" | head -1 | cut -d ' ' -f 3
      - run: gh workflow view "$GITHUB_WORKFLOW" | head -2 | tail -1 | cut -d ' ' -f 2
      - run: gh workflow view "$GITHUB_WORKFLOW" --yaml | tee workflow.yml
      - run: echo "::set-output name=id::$(yq '.on.workflow_dispatch.inputs.id.default' workflow.yml)"
        id: inputs
      - run: echo $ID
        env:
          ID: ${{ steps.inputs.outputs.id }}
