name: Self

on:
  push:
    paths:
      - .github/workflows/self.yml
  workflow_dispatch:
    inputs:
      input1:
        default: value1

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - run: gh workflow list
