name: Self

on:
  push:
    paths:
      - .github/workflows/self.yml
  workflow_dispatch:
    inputs:
      input1:
        default: value1

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - run: printenv
      - run: gh workflow view $GITHUB_WORKFLOW | head -1 | cut -f 3
      - run: gh workflow view $GITHUB_WORKFLOW --yaml | tee workflow.yml
      - run: yq '.on.workflow_dispatch.inputs.input1.default' workflow.yml
        id: workflow
