name: Semantic versioning

on:
  workflow_dispatch:
    inputs:
      increment:
        description: Semantic versioning
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}
      increment: ${{ github.event.inputs.increment }}

    steps:
      - run: echo $semantic
      - run: gh api /repos/${GITHUB_REPOSITORY}/releases/latest
      - run: |
          tag=$(gh api /repos/${GITHUB_REPOSITORY}/releases/latest --jq '.tag_name')
          echo "version=$tag" >> $GITHUB_ENV
      # cookbenjamin/update-version@v1.0.1 はちょっと使いにくかった
      - run: |
          set -x
          
          if [[ ${version} =~ ^(v?)([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            prefix=${BASH_REMATCH[1]}
            major=${BASH_REMATCH[2]}
            minor=${BASH_REMATCH[3]}
            patch=${BASH_REMATCH[4]}
          fi
          
          shopt -s nocasematch
          case "$increment" in
            "major")
              ((++major)); minor=0; patch=0;;
            "minor")
              ((++minor)); patch=0;;
            "patch")
              ((++patch));;
          esac
          
          next_version="${prefix}${major}.${minor}.${patch}"
          echo $next_version
