name: Semantic versioning

on:
  workflow_dispatch:
    inputs:
      semantic:
        description: Semantic versioning
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - run: echo $semantic
        env:
          semantic: ${{ github.event.inputs.semantic }}
      - run: gh api /repos/${GITHUB_REPOSITORY}/releases/latest
      - id: current-version
        run: |
          tag=$(gh api /repos/${GITHUB_REPOSITORY}/releases/latest --jq '.tag_name')
          echo "set-output:: name=version::$tag"
      - id: increment-version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: 1.0.0
          increment-version-fragment: PATCH
      - run: echo ${{ steps.increment-version.outputs.updated-version }}
