name: Serverless

on:
  push:
    paths:
      - .github/workflows/serverless.yml
      - serverless/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: npm --version
      - run: npm install -g serverless
      - run: serverless --version
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1
      - run: serverless deploy
        working-directory: serverless
