name: Serverless

on:
  push:
    paths:
      - .github/workflows/serverless.yml
      - serverless/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
      - uses: snow-actions/serverless-deploy@v1.0.0
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1
          working-directory: serverless
