name: Serverless

on:
  push:
    paths:
      - .github/workflows/serverless.yml
      - serverless/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: npm --version
      - run: npm install -g serverless
      - run: serverless --version
      - uses: actions/checkout@v3
      - run: serverless deploy
        working-directory: serverless
