name: Setup Jenkins

on:
  push:
    paths:
      - .github/workflows/setup-jenkins.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: snow-actions/setup-jenkins@setup-jenkins
      - run: curl --head http://localhost:8080/
