name: Setup Jenkins

on:
  push:
    paths:
      - .github/workflows/setup-jenkins.yml
      - jenkins/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: snow-actions/setup-jenkins@v0.1.0
        with:
          jenkins_home: jenkins/jenkins_home
      - run: curl --head http://localhost:8080/
      - run: ls -la jenkins/jenkins_home/
      - run: ls -la jenkins/jenkins_home/jobs/
      
      # Remote Access API
      - run: |
          crumb=$(curl -s -c cookie http://localhost:8080/crumbIssuer/api/json)
          echo "CRUMB_HEADER=$(echo $crumb | jq -r '.crumbRequestField'): $(echo $crumb | jq -r '.crumb')" >> $GITHUB_ENV
      - run: curl -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/api/json | jq '.jobs'
      - run: curl -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/build
      
      # Jenkins CLI
      - run: wget http://localhost:8080/jnlpJars/jenkins-cli.jar
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket help
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket version
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket who-am-i
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-jobs
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-1
      
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket console job-1 -f
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-1 -f -v
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-1 -f -v -p pr_number=200
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-plugins
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-plugins parameter-separator
        continue-on-error: true
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket install-plugin parameter-separator -deploy
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-plugins
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-plugins parameter-separator
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket copy-job job-1 job-2
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket list-jobs
      - run: java -jar jenkins-cli.jar -s http://localhost:8080/ -webSocket build job-2 -f -v -p pr_number=201
      
      # Info
      - run: docker ps
      - run: printenv
