name: Slack

on:
  push:
    paths:
      - .github/workflows/slack.yml
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo "hello" > hello
      - run: |
          set -x
          curl -H "Authorization: Bearer $token" -F "file=@hello" --form-string "initial_comment=$comment" -F channels=$channels https://slack.com/api/files.upload
        env:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          comment: <@${{ secrets.SLACK_USER_ID }}> メンション
          channels: sandbox

  app:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        id: slack
        with:
          channel-id: '#sandbox'
          slack-message: "Hello, Slack App!"
#       - uses: slackapi/slack-github-action@v1.18.0
#         id: slack
#         with:
#           channel-id: '#sandbox'
#           payload: |
#             {
#               "text": "Hello, Slack App!",
#               "attachments": [
#                 {
#                   "color": "good",
#                   "title": "title",
#                   "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
#                   "text": "description"
#                 }
#               ]
#             }
#       - uses: slackapi/slack-github-action@v1.18.0
#         with:
#           channel-id: '#sandbox'
#           payload: |
#             {
#               "text": "Reply",
#               "thread_ts": "${{ steps.slack.outputs.time }}"
#             }

  incoming-webhook:
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        id: slack
        with:
          payload: |
            {
              "text": "Hello, Incoming Webhook!",
              "attachments": [
                {
                  "color": "good",
                  "title": "title",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "text": "description"
                }
              ]
            }
#       - uses: slackapi/slack-github-action@v1.18.0
#         with:
#           payload: |
#             {
#               "text": "Reply",
#               "thread_ts": "${{ steps.slack.outputs.time }}"
#             }
