name: Slack

on:
  push:
    paths:
      - .github/workflows/slack.yml
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Hello, GitHub Actions!",
              "attachments": [
                {
                  "color": "good",
                  "title": "title",
                  "title_link": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"
                  "text": "description"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
