name: Slack

on:
  push:
    paths:
      - .github/workflows/slack.yml
  workflow_dispatch:

jobs:
  post:
    runs-on: [ self-hosted, Linux, CI ]
    timeout-minutes: 1

    steps:
      - uses: slackapi/slack-github-action@v1.18.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
