name: Summary

on:
  push:
    paths:
      - .github/workflows/summary.yml

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - run: |
          echo 'Title' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo 'Body' >> $GITHUB_STEP_SUMMARY
