name: Windows

on:
  push:
    paths:
      - .github/workflows/windows.yml

jobs:
  powershell:
    runs-on: windows-latest
    timeout-minutes: 1

    steps:
      - run: cat $env:GITHUB_EVENT_PATH
      - run: echo "test" > test
      - run: Test-Path test || exit 1
      - run: Test-Path none || exit 1
      
      - uses: actions/checkout@v3
      - uses: snow-actions/git-config-user@v1.0.0
      - run: git config user.name
      - run: git config user.email
      - run: echo "test" > test.txt
      - run: git add .
      - run: git commit -m "test"
