name: Windows

on:
  push:
    paths:
      - .github/workflows/windows.yml

jobs:
  powershell:
    runs-on: windows-latest
    timeout-minutes: 1

    steps:
      - run: cat $env:GITHUB_EVENT_PATH
      - run: echo "test" > test
      - run: Test-Path test || exit 1
      - run: Test-Path none || exit 1
